name: Minikube Setup CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Frontend Image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        tags: notes-frontend:latest
        push: false

    - name: Build Backend Image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        tags: notes-backend:latest
        push: false

    # - name: Start Minikube
    #   run: minikube start --driver=docker

    # - name: Show Kubernetes nodes
    #   run: kubectl get nodes

    - name: Apply Configuration Files
      run: |
        ls
        cd k8s
        minikube kubectl -- apply -f backend-pv.yaml
        minikube kubectl -- apply -f backend-deployment.yaml
        minikube kubectl -- apply -f frontend-deployment.yaml
        minikube kubectl -- apply -f services.yaml


    - name: Add ingress in minikube
      run: |
        cd k8s
        minikube addons enable ingress
        minikube kubectl -- apply -f ingress.yaml




